# Generated by Django 5.0 on 2023-12-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
